// Generated by BBNF — do not edit.

// ── Runtime types ────────────────────────────────────────────────

interface ParserState {
  input: string;
  offset: number;
}

interface Span {
  start: number;
  end: number;
}

function span(start: number, end: number): Span {
  return { start, end };
}

function createState(input: string): ParserState {
  return { input, offset: 0 };
}

// ── Grammar types ───────────────────────────────────────────────

type timelineLengthValue =
  | { tag: "timelineLength"; value: Span };

// ── Hoisted regex constants ──────────────────────────────────────

const __RE0 = new RegExp("[aA]uto|[+-]?(?:\\d+\\.?\\d*|\\.\\d+)(?:%|[a-zA-Z]+)?", "y");

// ── Parser functions ─────────────────────────────────────────────

function __timelineLength(s: ParserState): timelineLengthValue | null {
  __RE0.lastIndex = s.offset;
const __re0_m = __RE0.exec(s.input);
let __re0 = null;
if (__re0_m) { __re0 = span(s.offset, __RE0.lastIndex); s.offset = __RE0.lastIndex; }

  const __body = __re0;
  return __body !== null ? ({ tag: "timelineLength" as const, value: __body } as unknown as timelineLengthValue) : null;
}

// ── Public API ──────────────────────────────────────────────────

export function parse(input: string): { result: timelineLengthValue | null; offset: number } {
  const s = createState(input);
  const result = __timelineLength(s);
  if (result === null || s.offset !== s.input.length) {
    return { result: null, offset: s.offset };
  }
  return { result, offset: s.offset };
}
