// SERVED MODEL: claude-opus-5[1m]
/**
 * ════════════════════════════════════════════════════════════════════════════
 * X.W1.b · GOLDEN INTEGRITY — the one-pixel clause, closed properly
 * ════════════════════════════════════════════════════════════════════════════
 *
 * W1.md §X.W1.b's sub-gate: *"a one-pixel hand-edit to one golden turns the
 * suite red, receipt in the wave log."*
 * W1.md's Hard Gate G-9: *"a hand-injected 20px block"* must not pass.
 *
 * Those two clauses want different instruments, and the difference is not
 * pedantry — it is the whole reason this file exists.
 *
 * The pixel comparison in `routes.visual.spec.ts` et al. asks *"does the product
 * still look like its golden?"* Its bar is `maxDiffPixels`, sized in
 * `tolerance.ts` to sit ABOVE the measured run-to-run floor of the capture and
 * BELOW G-9's 20-px unit. That bar answers G-9. It cannot answer the one-pixel
 * clause: a bar low enough to red on ONE differing pixel is a bar below the
 * measured noise floor, and a gate that reds on correct pages is a gate someone
 * turns off — which is this wave's Archaeology in one sentence.
 *
 * So the one-pixel clause gets the instrument it actually needs: a DIGEST. A
 * golden is an evidence artefact, and the question *"has this artefact been
 * altered?"* is answered by sha256, exactly, at any edit size down to one bit.
 * `scripts/visual/regenerate-goldens.mjs` writes every golden's sha256 into
 * `docs/tranches/X/evidence/w1/visual/MANIFEST.json` from the settled bytes, and
 * this spec recomputes them.
 *
 * The two gates are complementary and neither substitutes for the other:
 *
 *   a 20-px change in the PRODUCT    → the pixel comparison reds (G-9)
 *   a 1-px hand-edit to a GOLDEN     → this integrity check reds (the sub-gate)
 *   a golden deleted or added silently → this check reds (FM-12's family)
 *
 * And the coupling is structural, not clerical: the manifest is regenerated by
 * the same script that regenerates the goldens, in the same run, so a ratified
 * regeneration updates both and a tampered golden updates neither.
 */
import { createHash } from "node:crypto";
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { join, resolve } from "node:path";
import { test, expect } from "@playwright/test";

import { decodePng } from "../smoke/fixtures/frame-diff";

const REPO_ROOT = resolve(import.meta.dirname, "../..");
const GOLDEN_DIR = resolve(import.meta.dirname, "goldens", process.platform);
const MANIFEST = resolve(REPO_ROOT, "docs/tranches/X/evidence/w1/visual/MANIFEST.json");

interface ManifestGolden {
    path: string;
    name: string;
    bytes: number;
    sha256: string;
}

function manifestGoldens(): ManifestGolden[] | null {
    if (!existsSync(MANIFEST)) return null;
    const parsed = JSON.parse(readFileSync(MANIFEST, "utf8"));
    const platform = parsed.platforms?.[process.platform];
    return platform ? (platform.goldens as ManifestGolden[]) : null;
}

function onDisk(): string[] {
    if (!existsSync(GOLDEN_DIR)) return [];
    return readdirSync(GOLDEN_DIR)
        .filter((f) => f.endsWith(".png"))
        .sort();
}

test("every committed golden matches its manifest digest", () => {
    const recorded = manifestGoldens();
    // The manifest is written by the regeneration script from the settled bytes.
    // Its ABSENCE is itself a finding — goldens with no digest of record cannot
    // be proved to be the bytes anyone reviewed — so this fails rather than skips.
    expect(
        recorded,
        `no manifest entry for platform "${process.platform}" at ${MANIFEST}. ` +
            "Run: node scripts/visual/regenerate-goldens.mjs --manifest-only",
    ).not.toBeNull();

    const mismatches: string[] = [];
    for (const golden of recorded!) {
        const path = join(REPO_ROOT, golden.path);
        if (!existsSync(path)) {
            mismatches.push(`MISSING  ${golden.name}`);
            continue;
        }
        const bytes = readFileSync(path);
        const actual = createHash("sha256").update(bytes).digest("hex");
        if (actual !== golden.sha256) {
            mismatches.push(
                `ALTERED  ${golden.name}\n` +
                    `           manifest ${golden.sha256} (${golden.bytes} bytes)\n` +
                    `           on disk  ${actual} (${bytes.length} bytes)`,
            );
        }
    }

    expect(
        mismatches,
        "a golden differs from its recorded digest. Either it was hand-edited — in " +
            "which case this gate has done its job — or it was regenerated without " +
            "the manifest, in which case run scripts/visual/regenerate-goldens.mjs " +
            "--accept so the two are updated together.\n\n" +
            mismatches.join("\n"),
    ).toEqual([]);
});

/**
 * THE FLAT-FRAME BACKSTOP — a golden that is one colour is a picture of the
 * boot, not of the product.
 *
 * ─── Why this test exists, measured ─────────────────────────────────────────
 *
 * The first mint of this matrix committed TWO goldens that are a single flat
 * colour — the pre-mount ground gradient — and both were then asserted against
 * on every later run as if they were the product's appearance:
 *
 *   at-rest-gradient-gradient-390-dark-…          1 distinct colour
 *   at-rest-admin-admin-tags-palettes-390-dark-…  1 distinct colour
 *   every other cell of the 207                 ≥ 401 distinct colours
 *
 * (8-px sampling grid, counter capped at 401; the gap between 1 and 401 is the
 * whole population, with nothing in between.)
 *
 * `capture.ts`'s `assertRendered` refuses to TAKE such a photograph, and it is
 * a DOM predicate, so it cannot see a frame whose DOM is complete while the
 * compositor emitted nothing — a class this suite has measured under host load
 * (IC-16c). This test reads the COMMITTED BYTES and so it can. The two are
 * deliberately different instruments at different layers: one refuses to take
 * the picture, this one refuses to keep it.
 *
 * The floor is 16 distinct colours on an 8-px grid, which is 25× below the
 * smallest real cell and 16× above a flat frame — no real cell can approach it
 * from above, and no flat frame can reach it from below.
 */
const FLAT_FRAME_MIN_COLOURS = 16;

test("no committed golden is a single flat colour", () => {
    // 207 full decodes of up to 3440×1441 — measured at 32 s on this machine,
    // which is over the 120 s config default once a loaded host is allowed for.
    test.setTimeout(240_000);

    const flat: string[] = [];
    for (const name of onDisk()) {
        const image = decodePng(readFileSync(join(GOLDEN_DIR, name)));
        const seen = new Set<number>();
        outer: for (let y = 0; y < image.height; y += 8)
            for (let x = 0; x < image.width; x += 8) {
                const i = (y * image.width + x) * image.channels;
                seen.add(
                    (image.data[i] << 16) |
                        (image.data[i + 1] << 8) |
                        image.data[i + 2],
                );
                if (seen.size >= FLAT_FRAME_MIN_COLOURS) break outer;
            }
        if (seen.size < FLAT_FRAME_MIN_COLOURS)
            flat.push(`${name} — ${seen.size} distinct colour(s)`);
    }

    expect(
        flat,
        "a committed golden is (nearly) one flat colour. That is the pre-mount " +
            "ground, ratified as the product's appearance — the exact false " +
            "baseline this matrix shipped twice in its first mint. Re-run the " +
            "cell on an unloaded host and regenerate with " +
            "scripts/visual/regenerate-goldens.mjs --accept.\n\n" +
            flat.join("\n"),
    ).toEqual([]);
});

test("no golden exists that the manifest does not record", () => {
    const recorded = manifestGoldens();
    expect(recorded).not.toBeNull();
    const known = new Set(recorded!.map((g) => g.name));
    const unrecorded = onDisk().filter((name) => !known.has(name));
    expect(
        unrecorded,
        "goldens on disk with no manifest entry. An unrecorded golden is an " +
            "assertion nobody ratified — FM-12's shape, one directory further in.",
    ).toEqual([]);
});
