// SERVED MODEL: claude-opus-5-5
//
// X.P.W6.h — G-h1: the BBNF grammar against the shipping parser over the full corpus, MIRROR-DEFECTS 0.
//
// Corpus: the assay union (`assay-corpus.json`, the retired seam's 27,021 rows, sha-asserted) and the
// real-CSS arms (`real-corpus.json`: value.js's demo CSS, keyframes.js's CSS, value.js's test and WPT
// strings — generated by `build-corpus.mjs`, sha-asserted). Every cell of the six parse entries is
// classified by `differential.ts`; a RED cell no ruling explains is a mirror-defect.

import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";

import * as hand from "../../../src/css/grammar";
import { ENTRIES, RED_TRIGGERS, runEntry } from "./differential";

const HERE = path.dirname(new URL(import.meta.url).pathname);
const read = (file: string) => JSON.parse(readFileSync(path.join(HERE, file), "utf8"));
const digest = (rows: unknown) => createHash("sha256").update(JSON.stringify(rows)).digest("hex");

type Row = { s: string | { src: string } };
const sources = (rows: Row[]) => [...new Set(rows.map((r) => (typeof r.s === "string" ? r.s : r.s.src)))];

const CORPORA = [
    { name: "assay", file: "assay-corpus.json", sha: "e119d81be0d088ec6bd061c7079242f8443b7e1651e1abdebca3eba7c20ca094" },
    { name: "real", file: "real-corpus.json", sha: null },
] as const;

describe("X.P.W6.h — BBNF grammar ≡ shipping parser (G-h1)", () => {
    for (const corpus of CORPORA) {
        const data = read(corpus.file) as { rows: Row[]; rowsSha256: string };
        const inputs = sources(data.rows);

        it(`${corpus.name}: the corpus is the pinned one`, () => {
            expect(digest(data.rows)).toBe(data.rowsSha256);
            if (corpus.sha !== null) expect(data.rowsSha256).toBe(corpus.sha);
        });

        for (const entry of ENTRIES) {
            it(`${corpus.name} · ${entry}: MIRROR-DEFECTS 0`, () => {
                const row = runEntry(entry, inputs);
                const defects = row.misses.map((m) => `${m.verdict} ${JSON.stringify(m.input)} — ${m.why}`);
                console.log(`${corpus.name} · ${entry}: ${row.cells} cells · ${JSON.stringify(row.tally)} · rulings ${JSON.stringify(row.rulings)} · MIRROR-DEFECTS ${row.misses.length}`);
                expect(defects).toEqual([]);
            }, 300_000);
        }
    }

    // The instrument can fail: a candidate that moves one channel off the incumbent's reading is RED.
    it("falsifier: a planted value defect reads RED", () => {
        const planted = (s: string) => {
            const r = hand.parseCssColor(s);
            return r.ok ? { ...r, value: { ...r.value, alpha: r.value.alpha === 0.5 ? 0.25 : 0.5 } } : r;
        };
        const row = runEntry("parseCssColor", ["red", "#0f0", "rgb(1 2 3)"], planted);
        expect(row.misses.length).toBe(3);
        expect(row.misses.every((m) => RED_TRIGGERS.includes(m.verdict))).toBe(true);
    });
});
