// SERVED MODEL: claude-opus-5-5
//
// X.P.W7 `.o` (a) — THE F-b-4 CLASS, enumerated row by row (COHESION §0ck 1: accepted spec-correct; rowed in a
// dated DIVERGENCE-LEDGER section; stock-ASCII routing never reproduced). The class is DEFINED by difference:
//   sound   banked:jx-aot-pos     (flag-aware FIRST sets: a non-ASCII leading code unit routes by the grammar)
//   ascii   banked:jx-aot-pos-sa  (the same emitter emulating bbnf-lang 0.1.4's ASCII-only dispatch)
// Precondition: `ascii` reproduces the oracle with 0 mismatches, so every row where `sound` differs is F-b-4 and
// nothing else. Each row carries the oracle (0.1.4) answer, the sound answer and, for entry rows, the retired parser's.
//   node bench/paired/fb4.mjs   → oracle/F-b-4.json (+ the markdown rows on stdout)
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { BUILD, HERE, arm } from "./common.mjs";
import { canon } from "./oracle.mjs";

const run = (name) => {
    const out = path.join(BUILD, `equiv-${name.replace(":", "-")}.json`);
    try { execFileSync(process.execPath, [path.join(HERE, "equiv.mjs"), name, out], { stdio: "inherit" }); } catch { /* exit 1 = mismatches, read below */ }
    return JSON.parse(readFileSync(out, "utf8"));
};
const ascii = run("banked:jx-aot-pos-sa"), sound = run("banked:jx-aot-pos");
if (ascii.mismatches !== 0) throw new Error(`precondition: jx-aot-pos-sa must reproduce the oracle, read ${ascii.mismatches}`);
if (sound.rows.some((r) => r.nonAscii !== true)) throw new Error("a sound-routing mismatch on an ASCII-only source is not F-b-4");
const R = await arm("retired");
const rows = sound.rows.map((r) => {
    const e = r.section.startsWith("entry:") ? r.section.slice(6) : null;
    let retired = null;
    if (e) { try { retired = canon(R.fns[e](r.source)); } catch (x) { retired = { $throw: String(x?.message ?? x) }; } }
    return { section: r.section, key: r.key, source: r.source, oracle: r.golden, sound: r.arm, retired,
        soundAgreesRetired: e ? JSON.stringify(retired) === JSON.stringify(r.arm) : null, oracleAgreesRetired: e ? JSON.stringify(retired) === JSON.stringify(r.golden) : null };
});
const bySection = {};
for (const r of rows) bySection[r.section] = (bySection[r.section] ?? 0) + 1;
const doc = { note: "F-b-4 rows (COHESION §0ck 1), generated by bench/paired/fb4.mjs", total: rows.length,
    entryRows: rows.filter((r) => r.section.startsWith("entry:")).length, readerRows: rows.filter((r) => r.section.startsWith("reader:")).length, bySection, rows };
writeFileSync(path.join(HERE, "oracle", "F-b-4.json"), JSON.stringify(doc, null, 1) + "\n");
const brief = (v) => (v?.ok === true ? "ok" : v?.ok === false ? `refused ${v.diagnostics?.[0]?.code ?? ""} ${JSON.stringify(v.diagnostics?.[0]?.actual ?? "")}` : JSON.stringify(v)).slice(0, 90).replace(/\|/g, "\\|");
console.log(`F-b-4: ${doc.total} rows = ${doc.entryRows} entry + ${doc.readerRows} reader`, JSON.stringify(bySection));
rows.forEach((r, i) => console.log(`| ${i + 1} | \`${r.section}\` | ${JSON.stringify(r.source).replace(/\|/g, "\\|")} | ${brief(r.oracle)} | ${brief(r.sound)} | ${r.retired === null ? "n/a (reader)" : r.soundAgreesRetired ? "agrees with sound" : r.oracleAgreesRetired ? "agrees with 0.1.4" : "differs from both"} |`));
